import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "../context/ThemeContext";
import ClientWrapper from "../components/ClientWrapper";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientWrapper>
          <ThemeProvider>{children}</ThemeProvider>
        </ClientWrapper>
      </body>
    </html>
  );
}
