import type { EventDataType } from "./type/eventDataType"

export const eventsData: EventDataType[] = [
  {
    id: "1",
    title: "Unleashing XXible Nightlife",
    location: "Victoria Island, Lagos",
    date: "Fri, Feb 7",
    time: "9:00 PM",
    price: 50000,
    currency: "₦",
    attendingCount: 50,
    imageUrl: "/assets/featured/featured1.png",
    imageAlt: "Person wearing glowing neon mask at nightclub with vibrant lighting",
    categories: ["Girls Night", "Karaoke", "DJ Night"],
    brand: {
      name: "Quilox",
      description: "Explore nightlife in Lagos",
    },
  },
  {
    id: "2",
    title: "Afrobeats Rooftop Experience",
    location: "Lekki Phase 1, Lagos",
    date: "Sat, Feb 8",
    time: "6:00 PM",
    price: 35000,
    currency: "₦",
    attendingCount: 127,
    imageUrl: "/assets/featured/featured2.png",
    imageAlt: "Rooftop party with Afrobeats music and Lagos city skyline",
    categories: ["Afrobeats", "Rooftop", "Live DJ", "Cocktails"],
    brand: {
      name: "SkyLounge",
      description: "Premium rooftop experiences",
    },
  },
  {
    id: "3",
    title: "Neon Nights: Electronic Fusion",
    location: "Ikeja GRA, Lagos",
    date: "Sun, Feb 9",
    time: "7:30 PM",
    price: 25000,
    currency: "₦",
    attendingCount: 89,
    imageUrl: "/assets/featured/featured3.png",
    imageAlt: "Electronic music party with neon lights and laser show",
    categories: ["Electronic", "Techno", "Laser Show", "VIP"],
    brand: {
      name: "Pulse Club",
      description: "Electronic music destination",
    },
  },
  {
    id: "4",
    title: "Jazz & Wine Soirée",
    location: "Ikoyi, Lagos",
    date: "Thu, Feb 6",
    time: "10:00 PM",
    price: 45000,
    currency: "₦",
    attendingCount: 64,
    imageUrl: "/assets/featured/featured4.png",
    imageAlt: "Elegant jazz club with live band and wine tasting",
    categories: ["Jazz", "Live Music", "Wine Tasting", "Upscale"],
    brand: {
      name: "The Jazz Spot",
      description: "Sophisticated live music venue",
    },
  },
  {
    id: "5",
    title: "Lagos Beach Party Extravaganza",
    location: "Tarkwa Bay, Lagos",
    date: "Mon, Jun 22",
    time: "4:00PM",
    price: 20000,
    currency: "₦",
    attendingCount: 203,
    imageUrl: "/assets/featured/featured5.png",
    imageAlt: "Beach party with bonfire and sunset dancing",
    categories: ["Beach Party", "Sunset", "Bonfire", "Dancing"],
    brand: {
      name: "Waves Entertainment",
      description: "Beach party specialists",
    },
  },
  {
    id: "6",
    title: "Hip-Hop Cypher Night",
    location: "Surulere, Lagos",
    date: "Sun, Jun 25",
    time: "8:00PM",
    price: 15000,
    currency: "₦",
    attendingCount: 156,
    imageUrl: "/assets/featured/featured6.png",
    imageAlt: "Hip hop cypher with rappers performing on stage",
    categories: ["Hip-Hop", "Live Performance", "Cypher", "Underground"],
    brand: {
      name: "Urban Vibes",
      description: "Street culture and music",
    },
  },
]
