import type { EventDataType } from "../../../../src/components/utility/cards/event-card2/type/eventDataType";

export const eventsData: EventDataType[] = [
  {
    id: "1",
    title: "Unleashing XXible Nightlife",
    location: "Victoria Island, Lagos",
    date: "Jun 13",
    time: "6PM",
    price: 50000,
    currency: "₦",
    interestedCount: 50,
    imageUrl: "/assets/featured/featured1.png",
    imageAlt: "Person wearing glowing neon mask at nightclub with vibrant lighting",
    brand: {
      name: "Quilox",
      description: "Explore nightlife in Lagos",
    },
  },
  {
    id: "2",
    title: "Afrobeats Rooftop Experience",
    location: "Lekki Phase 1, Lagos",
    date: "Jun 15",
    time: "8PM",
    price: 35000,
    currency: "₦",
    interestedCount: 127,
    imageUrl: "/assets/featured/featured2.png",
    imageAlt: "Rooftop party with Afrobeats music and Lagos city skyline",
    brand: {
      name: "SkyLounge",
      description: "Premium rooftop experiences",
    },
  },
  {
    id: "3",
    title: "Neon Nights: Electronic Fusion",
    location: "Ikeja GRA, Lagos",
    date: "Jun 18",
    time: "9PM",
    price: 25000,
    currency: "₦",
    interestedCount: 89,
    imageUrl: "/assets/featured/featured3.png",
    imageAlt: "Electronic music party with neon lights and laser show",
    brand: {
      name: "Pulse Club",
      description: "Electronic music destination",
    },
  },
  {
    id: "4",
    title: "Jazz & Wine Soirée",
    location: "Ikoyi, Lagos",
    date: "Jun 20",
    time: "7PM",
    price: 45000,
    currency: "₦",
    interestedCount: 64,
    imageUrl: "/assets/featured/featured4.png",
    imageAlt: "Elegant jazz club with live band and wine tasting",
    brand: {
      name: "The Jazz Spot",
      description: "Sophisticated live music venue",
    },
  },
  {
    id: "5",
    title: "Lagos Beach Party Extravaganza",
    location: "Tarkwa Bay, Lagos",
    date: "Jun 22",
    time: "4PM",
    price: 20000,
    currency: "₦",
    interestedCount: 203,
    imageUrl: "/assets/featured/featured5.png",
    imageAlt: "Beach party with bonfire and sunset dancing",
    brand: {
      name: "Waves Entertainment",
      description: "Beach party specialists",
    },
  },
  {
    id: "6",
    title: "Hip-Hop Cypher Night",
    location: "Surulere, Lagos",
    date: "Jun 25",
    time: "8PM",
    price: 15000,
    currency: "₦",
    interestedCount: 156,
    imageUrl: "/assets/featured/featured6.png",
    imageAlt: "Hip hop cypher with rappers performing on stage",
    brand: {
      name: "Urban Vibes",
      description: "Street culture and music",
    },
  },
]
